### ISSUE TITLE
Seg fault with -F

### ISSUE THREAD

**Issue by jmeppley** [hallamlab/LAST-Plus#1]
When I try to search a protein database with a nucleotide query, I get a segmentation fault. It works fine with the original lastal. I get the same issue with v1.0 and master.

```
 $ lastdb+ -v -p test.ldb test.genes.fasta
lastdb: reading test.genes.fasta...
lastdb: writing...
lastdb: sorting...
lastdb: bucketing...
lastdb: writing...
lastdb: done!

 $ lastal+ -v -F 15 -o test.lastx+ test.ldb test.reads.fasta
lastal: calculating matrix probabilities...
lastal: lambda=0.353941
Segmentation fault: 11

 $ lastal -v -F 15 -o test.lastx test.ldb test.reads.fasta
lastal: calculating matrix probabilities...
lastal: lambda=0.353941
lastal: reading test.ldb...
lastal: reading test.reads.fasta...
lastal: translating...
lastal: scanning...
lastal: initial matches=21648
lastal: gapless extensions=19149
lastal: gapless alignments=200
lastal: redone gapless alignments=200
lastal: gapped extensions=171
lastal: gapped alignments=151
lastal: nonredundant gapped alignments=151
lastal: finishing...
lastal: reverse complementing...
lastal: translating...
lastal: scanning...
lastal: initial matches=20984
lastal: gapless extensions=19590
lastal: gapless alignments=150
lastal: redone gapless alignments=150
lastal: gapped extensions=126
lastal: gapped alignments=62
lastal: nonredundant gapped alignments=62
lastal: finishing...
lastal: query batch done!
```

**Comment by nielshanson** [comment]
Hey John,

If your comfortable sharing. Could you host the database and input (on dropbox or something) so we can reproduce the bug on our end?

Thanks,
Niels

**Comment by jmeppley** [comment]
Of course. Here are some smaller files that reproduce the problem:
https://dl.dropboxusercontent.com/u/9325989/lastplus/test.genes.fasta
https://dl.dropboxusercontent.com/u/9325989/lastplus/test.reads.fasta

**Comment by dongjaek** [comment]
Hey John, 

I've pushed a functional version which does DNA->protein alignment onto the lastx branch. 
Could you get back to me if this resolved your problem? 

EDIT: Please pull from the master branch and try again.

**Comment by jmeppley** [comment]
Thanks! 
However, it only works for "-f 0" and "-f 2", but not "-f 1". It just returns nothing. No error message of any kind.

**Comment by dongjaek** [comment]
LAST+ is not yet completely polished technology as the paper is still in revision stages. There are some features which may not make it into LAST+ in the very near future due to very severe time and manpower constraints. 

Full functionality for f1 is currently not implemented.

f2 is the default option for output so it need not be specified if you want BLAST-like output.

I apologize for any inconveniences that the current state of the software may cause. I hope that the portions which are currently functional live up to your expectations.
Please remember to do a fresh pull from master, make clean and make before any new runs.

**Comment by jmeppley** [comment]
Thanks. I don't need -f 1. I just thought I should let you know. With the "lastx" fix, LAST-plus is now in a state that is extremely useful to us. Thanks for making it happen.

Perhaps a "not yet implemented" message would avoid confusion and prevent future unnecessary issue reports.
